/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#4cd7f6',
        'primary-container': '#0f5132',
        'on-primary-fixed-variant': '#0f5132',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#dae2fd',
        'on-surface-variant': '#404942',
        background: '#faf8ff',
        'on-tertiary-fixed-variant': '#004e5c',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'on-error-container': '#93000a',
        'inverse-surface': '#283044',
        outline: '#707971',
        'on-surface': '#131b2e',
        'outline-variant': '#c0c9c0',
        'on-primary-container': '#84c39b',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#002111',
        'surface-tint': '#2d6a48',
        'on-secondary-container': '#006f66',
        'on-secondary-fixed': '#00201d',
        'primary-fixed-dim': '#95d4ac',
        'on-secondary-fixed-variant': '#005049',
        'surface-container-high': '#e2e7ff',
        'surface-container': '#eaedff',
        'secondary-fixed': '#89f5e7',
        error: '#ba1a1a',
        surface: '#faf8ff',
        'tertiary-fixed': '#acedff',
        tertiary: '#003640',
        'secondary-fixed-dim': '#6bd8cb',
        'primary-fixed': '#b0f1c7',
        'tertiary-container': '#004e5c',
        primary: '#003820',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'on-tertiary-fixed': '#001f26',
        'surface-variant': '#dae2fd',
        'on-error': '#ffffff',
        'on-tertiary-container': '#30c5e3',
        'secondary-container': '#86f2e4',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'error-container': '#ffdad6',
        secondary: '#006a61',
        'inverse-primary': '#95d4ac',
        'on-background': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '1.25rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'gutter-mobile': '0.75rem',
        'margin-mobile': '1rem',
        margin: '2rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'metric-display': ['JetBrains Mono'],
        'label-caps': ['Inter'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'display-hero-mobile': ['Plus Jakarta Sans'],
        'technical-data': ['JetBrains Mono'],
        'headline-lg': ['Plus Jakarta Sans'],
        'display-hero': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'metric-display': ['28px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'technical-data': ['13px', { lineHeight: '18px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
